"""Add additional indexes.

Revision ID: 7023df707a28
Revises: 2d58f8ffc51a
Create Date: 2025-06-08 19:02:09.794130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7023df707a28'
down_revision: Union[str, None] = '2d58f8ffc51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_computers_cpid'), 'computers', ['cpid'], unique=False)
    op.create_index(op.f('ix_computers_user_id'), 'computers', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_attachments_computer_id'), 'project_attachments', ['computer_id'], unique=False)
    op.create_index(op.f('ix_project_attachments_project_id'), 'project_attachments', ['project_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_project_attachments_project_id'), table_name='project_attachments')
    op.drop_index(op.f('ix_project_attachments_computer_id'), table_name='project_attachments')
    op.drop_index(op.f('ix_computers_user_id'), table_name='computers')
    op.drop_index(op.f('ix_computers_cpid'), table_name='computers')
    # ### end Alembic commands ###
