"""Add last connection tracking to computers.

Revision ID: cbb27e63e213
Revises: e49fdb0c3016
Create Date: 2025-06-17 21:17:06.938278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cbb27e63e213'
down_revision: Union[str, None] = 'e49fdb0c3016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    connection = op.get_bind()
    connection.execute(
        sa.text(
            "UPDATE computers SET last_connected_at = updated_at"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'last_connected_at')
    # ### end Alembic commands ###
