"""Add vacation override setting to computers.

Revision ID: aa0c01e688a2
Revises: 2f313d453572
Create Date: 2025-06-23 22:15:58.848414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'aa0c01e688a2'
down_revision: Union[str, None] = '2f313d453572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    with op.batch_alter_table('computers', schema=None) as batch_op:
        # Add the vacation_override column with a default value
        batch_op.add_column(sa.Column('vacation_override', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'vacation_override')
    # ### end Alembic commands ###
